name: Incayellow
favicon: null
layout_spectrum: 0.26143762189894915
typography_spectrum: 0.10786391631700099
title: Incayellow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7998839947395027
  lightness: 0.2552361646667123
  saturation: 0.10961725772358477
  rhythmicContrast: 0.8629027472343296
purpose: []
